- hosts: controlplane ## Local onde será executado
  become: true ## Permissionamento de usuário root
  tasks: ## Sequência de tarefas que será executada
    - name: inicializando o cluster ## Inicializa o cluster executando os comandos abaixo
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU,Mem >> cluster_initialized.txt
      args:
        chdir: $HOME ## Diretório utilizado

    - name: criando .kube ## Cria um diretório seguindo as especificações utilizando o usuário 'ubuntu'
      become_user: ubuntu 
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copiando config ## Copia as informações para o diretório criado anteriormente utilizando o usuário 'ubuntu'
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: habilitando plugin CNI ## Habilita o plugin CNI utilizando o usuário 'ubuntu'
      become_user: ubuntu
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME